### ISSUE TITLE
progressive Resize interferes with exisiting sampler in pytorch dataloader (batch_sampler)

### ISSUE THREAD

**Issue by souravdalai18** [warner-benjamin/fastxtend#16]

**Comment by warner-benjamin** [comment]
@souravdalai18 could you provide some more details and a minimal reproduction? `ProgressiveResize` doesn't apply until after the batch has been collated and has been transferred to the GPU.

**Comment by warner-benjamin** [comment]
I added a preallocate flag to `ProgressiveResize` in 23c07b0 which might help with this issue.

Closing due to inability to replicate. Please reopen with details if the issue persists in the next fastxtend release.
