### ISSUE TITLE
StableAdamW: Missing divisor in RMS computation

### ISSUE THREAD

**Issue by EricZimmermann** [warner-benjamin/fastxtend#27]
Hello

It seems as though there is a minor error in computing RMS in Stable Adam:

RMS is computed as:
 https://github.com/warner-benjamin/fastxtend/blob/e6b2c39a9d2b70ec1038a6142d79c39765795806/fastxtend/optimizer/stableadam.py#L53

And is missing a normalization coefficient for the mean:
`rms = torch.norm(p.grad.data.div(root_sqr_avg.maximum(eps_t)), 2) / math.sqrt(p.grad.data.div.numel())`

as per 
![image](https://github.com/warner-benjamin/fastxtend/assets/23340179/8636988e-9997-44bb-b9dd-e2fa165c653a)

Additionally, another eps can be added in the final normalization.

**Comment by warner-benjamin** [comment]
I'm in the process of porting over the fastxtend optimizers to use the [optimi](<https://github.com/warner-benjamin/optimi>) implementations, which should resolve this.

**Comment by warner-benjamin** [comment]
@EricZimmermann #28 tracks the progress of porting over the fastxtend optimizers to use the [optimi](<https://github.com/warner-benjamin/optimi>) implementations
